
spring:
  application:
    name: product-service

  liquibase:
    change-log: classpath:db/changelog/changelog.xml
    url: jdbc:postgresql://localhost:9000/shop
    user: admin
    password: online_shop
    enabled: true
    default-schema: product_management
    liquibase-schema: product_management_migrations

  datasource:
    url: jdbc:postgresql://localhost:9000/shop
    username: admin
    password: online_shop

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: ${spring.liquibase.liquibase-schema}
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: info
    ru.puchinets.userservice.controller.rest: trace
    ru.puchinets.userservice.service.impl: trace
  file:
    name: product-service.log
    path: /logs/product-service/

server:
  port: 9002
springdoc:
  swagger-ui:
    path: /swagger/swagger-ui.html
