
spring:
  application:
    name: product-service

  liquibase:
    change-log: classpath:db/changelog/changelog.xml
    url: ${DB_URL:jdbc:postgresql://localhost:9000/shop}
    user: ${DB_USER:admin}
    password: ${DB_PASS:online_shop}
    enabled: true
    default-schema: product_management
    liquibase-schema: product_management_migrations

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:9000/shop}
    username: ${DB_USER:admin}
    password: ${DB_PASS:online_shop}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: ${spring.liquibase.default-schema}
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: info
    ru.puchinets.productservice.controller.rest: trace
    ru.puchinets.productservice.service.impl: trace
  file:
    name: product-service.log
    path: /logs/product-service/

server:
  port: 9002
springdoc:
  swagger-ui:
    path: /swagger/swagger-ui.html
