
spring:
  application:
    name: rates-service
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
      database: 0

logging:
  level:
    root: info
    ru.puchinets.ratesservice.aspects: trace
    ru.puchinets.ratesservice.controller.rest: trace
    ru.puchinets.ratesservice.service.impl: trace
  file:
    name: order-service.log
    path: /logs/order-service/
server:
  port: 9004
springdoc:
  swagger-ui:
    path: /swagger/swagger-ui.html
