
spring:
  application:
    name: user-service
  liquibase:
    change-log: classpath:db/changelog/changelog.xml
    url: jdbc:postgresql://localhost:9000/shop
    user: admin
    password: online_shop
    enabled: true
    default-schema: user_management
    liquibase-schema: user_management_migrations
  datasource:
    url: jdbc:postgresql://localhost:9000/shop
    username: admin
    password: online_shop
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: ${spring.liquibase.liquibase-schema}
        dialect: org.hibernate.dialect.PostgreSQLDialect



#application:
#  user-service:
#    url: ${USER_SERVICE_URL:http://localhost:9000}
server:
  port: 9001
