
spring:
  application:
    name: order-service

  liquibase:
    change-log: classpath:db/changelog/changelog.xml
    url: jdbc:postgresql://localhost:9000/shop
    user: admin
    password: online_shop
    enabled: true
    default-schema: order_management
    liquibase-schema: order_management_migrations

  datasource:
    url: jdbc:postgresql://localhost:9000/shop
    username: admin
    password: online_shop

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: ${spring.liquibase.liquibase-schema}
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: info
    ru.puchinets.orderservice.controller.rest: trace
    ru.puchinets.orderservice.service.impl: trace
  file:
    name: order-service.log
    path: /logs/order-service/

server:
  port: 9003
springdoc:
  swagger-ui:
    path: /swagger/swagger-ui.html
application:
  product-service:
    path: ${PRODUCT_SERVICE_PATH:http://localhost:9002}
    url: ${PRODUCT_SERVICE_URL:/products}